### ISSUE TITLE
`nil` should be semantically equivalent to the `empty` item

### ISSUE THREAD

**Issue by markusschlegel** [active-group/reacl-c#1]
Returning `nil` where an item is expected raises an error. I suggest that nil should behave like `empty`, making code like the following valid:

```clojure
(c/dynamic
     (fn [st]
       (when (some-condition st)
         some-item)))
```

Currently, this code snippet raises an error. In order to achieve the desired effect one has to write `(if (some-condition st) some-item empty)`.

"Nil-punning" is a hotly-debated topic, but I argue that in this case it is the correct semantics, largely because the following code snippet is already valid in the current model:

```clojure
(c/dynamic
 (fn [st]
   (c/fragment
    (when (some-condition st)
      some-item))))
```

Since `fragment` is fine with nils and just ignores them.

**Comment by dfrese** [comment]
I now made it not only semantically equivalent, but also referentially equal, i.e. empty fragments are nil. That also reliefs dom and fragment ctors from fiddling around with their argument lists (might be beneficial for performance), and gives each child a more stable and predictable position (needed for some message util I have in mind; and also good for React's diffing).
